[theme]
primaryColor = "#FF9F00"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 5
enableCORS = true

GROQ_API_KEY="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"